import {create} from 'zustand';import {useEffect} from 'react';import type {User} from '@supabase/supabase-js';import {supabase} from '../lib/supabase';import {usePortal,type Run} from '../lib/store';import {isGameId,type GameId} from '../lib/catalog';
type Profile={id:string;display_name:string;avatar:number};
type Account={user:User|null;ready:boolean;profile:Profile|null;favorites:GameId[];recent:GameId[];runs:Run[];achievements:string[];syncError:boolean};
export const useAccount=create<Account>(()=>({user:null,ready:false,profile:null,favorites:[],recent:[],runs:[],achievements:[],syncError:false}));
export async function refreshAccount(uid:string){if(!supabase)return;const [profile,favorites,recent,scores,achievements]=await Promise.all([supabase.from('profiles').select('id,display_name,avatar').eq('id',uid).single(),supabase.from('favorites').select('game_id').eq('user_id',uid),supabase.from('recently_played').select('game_id').eq('user_id',uid).order('played_at',{ascending:false}),supabase.from('scores').select('game_id,score,duration_ms,created_at').eq('user_id',uid).order('created_at',{ascending:false}).limit(300),supabase.from('player_achievements').select('achievement_id').eq('user_id',uid)]);if(useAccount.getState().user?.id!==uid)return;if([profile,favorites,recent,scores,achievements].some(r=>r.error)){useAccount.setState({syncError:true});return}useAccount.setState({profile:profile.data,favorites:(favorites.data||[]).map(f=>f.game_id).filter(isGameId),recent:(recent.data||[]).map(f=>f.game_id).filter(isGameId),runs:(scores.data||[]).filter(s=>isGameId(s.game_id)).map(s=>({game:s.game_id as GameId,score:s.score,duration:s.duration_ms/1000,date:s.created_at})),achievements:(achievements.data||[]).map(a=>a.achievement_id),syncError:false})}
export function AuthBridge(){const user=useAccount(s=>s.user);useEffect(()=>{if(!supabase){useAccount.setState({ready:true});return}let active=true;const {data}=supabase.auth.onAuthStateChange((event,session)=>{if(!active)return;useAccount.setState({user:session?.user||null,ready:true});if(event==='PASSWORD_RECOVERY')window.location.replace('/reset-password')});void supabase.auth.getSession().then(({data,error})=>{if(active)useAccount.setState({user:data.session?.user||null,ready:true,syncError:!!error})});return()=>{active=false;data.subscription.unsubscribe()}},[]);
useEffect(()=>{if(!user||!supabase){useAccount.setState({profile:null,favorites:[],recent:[],runs:[],achievements:[]});return}const uid=user.id;let active=true;let unsubscribe:()=>void=()=>{};void (async()=>{await refreshAccount(uid);const result=await supabase!.from('player_preferences').select('language,theme').eq('user_id',uid).single();if(!active)return;if(result.error){useAccount.setState({syncError:true});return}usePortal.setState({language:result.data.language,theme:result.data.theme});unsubscribe=usePortal.subscribe((next,prev)=>{if(next.theme===prev.theme&&next.language===prev.language)return;void supabase!.from('player_preferences').upsert({user_id:uid,language:next.language,theme:next.theme}).then(({error})=>{if(active&&error)useAccount.setState({syncError:true})})})})();return()=>{active=false;unsubscribe()}},[user]);return null}
export function useFavorites(){const account=useAccount();const local=usePortal(s=>s.favorites);const values=account.user?account.favorites:local;const toggle=async(id:GameId)=>{const user=useAccount.getState().user;if(!user||!supabase){usePortal.getState().toggleFavorite(id);return}const previous=useAccount.getState().favorites;const remove=previous.includes(id);useAccount.setState({favorites:remove?previous.filter(f=>f!==id):[...previous,id]});const result=remove?await supabase.from('favorites').delete().eq('user_id',user.id).eq('game_id',id):await supabase.from('favorites').insert({user_id:user.id,game_id:id});if(result.error&&useAccount.getState().user?.id===user.id)useAccount.setState({favorites:previous,syncError:true})};return {favorites:values,toggle}}
export const avatarColors=['#e5b75d','#79b8ad','#ab9cdc','#dc8d9c','#82adce','#aebd78'];

