// @vitest-environment node
import {PGlite} from '@electric-sql/pglite';import {readFileSync} from 'node:fs';import {beforeAll,afterAll,describe,it,expect} from 'vitest';
let db:PGlite;const alice='11111111-1111-4111-8111-111111111111',bob='22222222-2222-4222-8222-222222222222';
async function asUser(uid:string,sql:string,params:unknown[]=[]){await db.exec("reset role; set role authenticated;");await db.query("select set_config('request.jwt.claim.sub',$1,false)",[uid]);return db.query(sql,params)}
async function admin(sql:string,params:unknown[]=[]){await db.exec('reset role');return db.query(sql,params)}
async function session(game='mango-catch'){const r=await asUser(alice,'select public.start_game($1) as id',[game]);const id=(r.rows[0] as {id:string}).id;await admin("update public.gameplay_sessions set started_at=clock_timestamp()-interval '30 seconds' where id=$1",[id]);return id}
beforeAll(async()=>{db=new PGlite();await db.exec("create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key,email text);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema public,auth to anon,authenticated;grant execute on function auth.uid() to anon,authenticated;");await db.exec(readFileSync('supabase/migrations/202609060001_foundation.sql','utf8'));await db.exec(readFileSync('supabase/migrations/202609060002_safe_names.sql','utf8'));await admin("insert into auth.users values($1,'alice@example.invalid'),($2,'bob@example.invalid')",[alice,bob])},30000);
afterAll(async()=>{await db?.close()});
describe('database security, executed in PostgreSQL',()=>{it('enables RLS on every exposed table',async()=>{const r=await admin("select tablename from pg_tables where schemaname='public' and not rowsecurity");expect(r.rows).toEqual([])});
it('public catalog hides unpublished game and translations',async()=>{await admin("insert into public.games(id,published) values('hidden',false)");await admin("insert into public.game_translations values('hidden','en','Hidden','Hidden')");await db.exec('set role anon');expect((await db.query("select * from public.games where id='hidden'")).rows).toHaveLength(0);expect((await db.query("select * from public.game_translations where game_id='hidden'")).rows).toHaveLength(0)});
it('denies guest score submission and direct client score inserts',async()=>{await db.exec('reset role;set role anon');await expect(db.query("select public.start_game('mango-catch')")).rejects.toThrow();await expect(asUser(alice,"insert into public.scores(user_id,game_id,session_id,score,duration_ms) values($1,'mango-catch',gen_random_uuid(),10,1000)",[alice])).rejects.toThrow()});
it('players cannot edit another profile or spoof markup',async()=>{expect((await asUser(alice,"update public.profiles set display_name='Stolen' where id=$1 returning id",[bob])).rows).toHaveLength(0);await expect(asUser(alice,"update public.profiles set display_name='<script>' where id=$1",[alice])).rejects.toThrow();await expect(asUser(alice,"update public.profiles set id=$1 where id=$2",[bob,alice])).rejects.toThrow()});
it('favorites enforce ownership and published games',async()=>{await expect(asUser(alice,"insert into public.favorites values($1,'mango-catch')",[bob])).rejects.toThrow();await expect(asUser(alice,"insert into public.favorites values($1,'hidden')",[alice])).rejects.toThrow();await asUser(alice,"insert into public.favorites values($1,'mango-catch')",[alice]);expect((await asUser(bob,'select * from public.favorites')).rows).toHaveLength(0)});
it('accepts plausible score once and awards achievement',async()=>{const id=await session();const r=await asUser(alice,'select public.submit_score($1,100,10000) as result',[id]);expect((r.rows[0] as {result:{accepted:boolean}}).result.accepted).toBe(true);const again=await asUser(alice,'select public.submit_score($1,100,10000) as result',[id]);expect((again.rows[0] as {result:{accepted:boolean}}).result.accepted).toBe(false);expect((await asUser(alice,'select * from public.player_achievements')).rows.length).toBeGreaterThan(0)});
it('rejects impossible, negative, future-duration and null scores and logs without public visibility',async()=>{for(const [score,duration] of [[99999,1000],[-1,1000],[100,999999],[null,1000]]){const id=await session();const r=await asUser(alice,'select public.submit_score($1,$2,$3) as result',[id,score,duration]);expect((r.rows[0] as {result:{accepted:boolean}}).result.accepted).toBe(false)}expect((await admin('select * from public.suspicious_score_events')).rows).toHaveLength(4);await expect(asUser(alice,'select * from public.suspicious_score_events')).rejects.toThrow()});
it('rejects other user session without consuming it',async()=>{const id=await session();const r=await asUser(bob,'select public.submit_score($1,10,1000) as result',[id]);expect((r.rows[0] as {result:{accepted:boolean}}).result.accepted).toBe(false);expect((await admin('select used from public.gameplay_sessions where id=$1',[id])).rows[0]).toEqual({used:false})});
it('public leaderboard excludes emails and user identifiers',async()=>{await db.exec('reset role;set role anon');const r=await db.query("select * from public.leaderboard('mango-catch')");expect(r.rows.length).toBe(1);expect(Object.keys(r.rows[0] as object).sort()).toEqual(['avatar','created_at','display_name','game_id','score']);await expect(db.query('select * from public.profiles')).rejects.toThrow()});
it('rate limits session creation and denies achievement forging',async()=>{await admin("delete from public.gameplay_sessions where user_id=$1 and used=false",[alice]);await admin("update public.gameplay_sessions set started_at=clock_timestamp()-interval '2 minutes'");for(let i=0;i<12;i++)await asUser(alice,"select public.start_game('mango-catch')");await expect(asUser(alice,"select public.start_game('mango-catch')")).rejects.toThrow('rate_limited');await expect(asUser(alice,"insert into public.player_achievements values($1,'explorer',now())",[alice])).rejects.toThrow()});
});
